### ISSUE TITLE
Homework Feedback JS2 Week 3

### ISSUE THREAD

**Issue by r0hitsharma** [fathionsons/hyf-homework#1]
Good work. Small feedback left below:

https://github.com/fathionsons/hyf-homework/blob/060837d9a8349eecc5026563c9b8f630b211f368/javascript/javascript2/week3/fastestpress/script.js#L20

Not a good way to name a variable, describe what it does.

https://github.com/fathionsons/hyf-homework/blob/060837d9a8349eecc5026563c9b8f630b211f368/javascript/javascript2/week3/up-warm/mainjavascript.js#L31

Also don't try to shorten variable names arbitrarily, just use the full word. Will help in searching by name much more later.

**Comment by fathionsons** [comment]
thanks for feedback
